#!/bin/bash
# scripts/setup_named_tunnel.sh
#
# ONE-TIME setup: register the voice agent with a Cloudflare named tunnel.
# After this completes, the URL NEVER rotates again — restart the server
# and the link is the same forever.
#
# Requires:
#   - A free Cloudflare account (https://dash.cloudflare.com/sign-up)
#   - cloudflared installed (already at /Users/ahs/Downloads/cloudflared)
#
# Time: ~5 minutes. Browser interaction required ONCE.

set -e

CFD="/Users/ahs/Downloads/cloudflared"
TUNNEL_NAME="voice-agent"
CERT_FILE="/Users/ahs/.cloudflared/cert.pem"
CREDS_DIR="/Users/ahs/.cloudflared"
CONFIG_FILE="$CREDS_DIR/config.yml"
PROJECT_DIR="/Users/ahs/Documents/Minimax_voice_agent/voice_agent"

red()    { printf "\033[31m%s\033[0m\n" "$*"; }
green()  { printf "\033[32m%s\033[0m\n" "$*"; }
yellow() { printf "\033[33m%s\033[0m\n" "$*"; }
bold()   { printf "\033[1m%s\033[0m\n" "$*"; }

bold "============================================================"
bold "Voice Agent — Cloudflare Named Tunnel Setup"
bold "============================================================"
echo

# -------------------------------------------------------------------------
# Step 1: preflight
# -------------------------------------------------------------------------
echo "▶ [1/5] preflight checks"
if [ ! -x "$CFD" ]; then
  red "✗ cloudflared not found at $CFD"
  exit 1
fi
echo "  cloudflared: $($CFD --version 2>&1 | head -1)"

if ! curl -s -o /dev/null -m 5 https://dash.cloudflare.com; then
  red "✗ cannot reach dash.cloudflare.com — check your network"
  exit 1
fi
echo "  network:    dash.cloudflare.com reachable ✓"
echo

# -------------------------------------------------------------------------
# Step 2: login (creates cert.pem on success)
# -------------------------------------------------------------------------
if [ -f "$CERT_FILE" ]; then
  yellow "▶ [2/5] cert.pem already exists — login skipped"
else
  bold "▶ [2/5] cloudflared login"
  echo "  → A browser tab will open at dash.cloudflare.com/argotunnel"
  echo "  → Log in with your Cloudflare account"
  echo "  → You can select 'No domain' / 'Use Cloudflare Account' for the"
  echo "    free cfargotunnel.com hostname"
  echo "  → Click 'Allow'"
  echo "  → Wait for the 'Success' page — then come back here"
  echo
  read -r -p "Press Enter when you're ready (or Ctrl-C to abort): "

  # Run login in foreground so the user sees the URL
  "$CFD" tunnel login || {
    red "✗ login failed"
    echo "  → Check that you clicked Allow in the browser"
    echo "  → Check that your email is verified: https://dash.cloudflare.com"
    exit 1
  }
  if [ ! -f "$CERT_FILE" ]; then
    red "✗ cert.pem not created after login"
    exit 1
  fi
  green "  ✓ cert.pem created"
fi
echo

# -------------------------------------------------------------------------
# Step 3: create the named tunnel
# -------------------------------------------------------------------------
TUNNEL_ID=$("$CFD" tunnel list 2>/dev/null | awk -v t="$TUNNEL_NAME" '$NF==t {print $1}')
if [ -n "$TUNNEL_ID" ]; then
  yellow "▶ [3/5] tunnel '$TUNNEL_NAME' already exists (id=$TUNNEL_ID)"
else
  bold "▶ [3/5] creating named tunnel '$TUNNEL_NAME'"
  "$CFD" tunnel create "$TUNNEL_NAME"
  TUNNEL_ID=$("$CFD" tunnel list 2>/dev/null | awk -v t="$TUNNEL_NAME" '$NF==t {print $1}')
  if [ -z "$TUNNEL_ID" ]; then
    red "✗ failed to create tunnel"
    exit 1
  fi
  green "  ✓ tunnel created: $TUNNEL_NAME (id=$TUNNEL_ID)"
fi
echo

# -------------------------------------------------------------------------
# Step 4: write config.yml and route DNS (free cfargotunnel.com)
# -------------------------------------------------------------------------
CRED_FILE=$(ls "$CREDS_DIR"/*.json 2>/dev/null | head -1)
if [ -z "$CRED_FILE" ]; then
  red "✗ no credentials JSON file found in $CREDS_DIR"
  exit 1
fi
green "  credentials: $CRED_FILE"

# Free hostname: <UUID>.cfargotunnel.com (no domain needed)
HOSTNAME="${TUNNEL_ID}.cfargotunnel.com"

cat > "$CONFIG_FILE" <<EOF
# Cloudflare tunnel config for voice-agent
# Generated by scripts/setup_named_tunnel.sh
tunnel: $TUNNEL_ID
credentials-file: $CRED_FILE
ingress:
  - hostname: $HOSTNAME
    service: http://localhost:8000
  - service: http_status:404
EOF
chmod 600 "$CONFIG_FILE"
green "  ✓ config written to $CONFIG_FILE"
green "  ✓ stable URL: https://$HOSTNAME"
echo

# -------------------------------------------------------------------------
# Step 5: write the launch script
# -------------------------------------------------------------------------
cat > "$PROJECT_DIR/scripts/run_named_tunnel.sh" <<EOF
#!/bin/bash
# Start (or restart) the voice agent with the stable named-tunnel URL.
# After this, the URL https://$HOSTNAME never changes between restarts.

PROJECT_DIR="$PROJECT_DIR"
CFD="$CFD"
CONFIG="$CONFIG_FILE"
LOG="/tmp/cloudflared-named.log"
URL_FILE="/tmp/cloudflared-named.url"
ENV_FILE="\$PROJECT_DIR/.env"

start() {
  pkill -f "cloudflared tunnel run" 2>/dev/null || true
  pkill -f "uvicorn app.main:app" 2>/dev/null || true
  sleep 2

  echo "▶ starting named tunnel…"
  nohup "\$CFD" --config "\$CONFIG" tunnel run voice-agent > "\$LOG" 2>&1 &
  echo "  cloudflared PID=\$!"
  sleep 5

  # Verify tunnel came up
  if ! curl -s -m 5 -o /dev/null -w "%{http_code}" "https://$HOSTNAME/" | grep -q 200; then
    echo "  ✗ tunnel didn't come up — check \$LOG"
    tail -20 "\$LOG"
    exit 1
  fi

  echo "▶ syncing PUBLIC_BASE_URL in .env…"
  sed -i '' "s|PUBLIC_BASE_URL=.*|PUBLIC_BASE_URL=https://$HOSTNAME|" "\$ENV_FILE"
  echo "\$HOSTNAME" > "\$URL_FILE"

  echo "▶ starting voice agent server…"
  cd "\$PROJECT_DIR"
  nohup uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 > /tmp/voice-agent.log 2>&1 &
  echo "  server PID=\$!"
  sleep 7

  echo ""
  green "✅ ready"
  echo "   WebRTC:    https://$HOSTNAME/browser-test"
  echo "   Dashboard: https://$HOSTNAME/dashboard"
  echo "   (these URLs will NEVER change between restarts)"
}

case "\${1:-start}" in
  start) start ;;
  stop)  pkill -f "cloudflared tunnel run"; pkill -f "uvicorn app.main:app" ;;
  *) echo "usage: \$0 {start|stop}"; exit 1 ;;
esac
EOF
chmod +x "$PROJECT_DIR/scripts/run_named_tunnel.sh"
green "  ✓ launch script: scripts/run_named_tunnel.sh"
echo

bold "============================================================"
bold "✅ Setup complete"
bold "============================================================"
echo
echo "Stable URL:  https://$HOSTNAME"
echo "Start with:  ./scripts/run_named_tunnel.sh"
echo
echo "Tunnel ID:    $TUNNEL_NAME / $TUNNEL_ID"
echo "Credentials:  $CRED_FILE"
echo
green "URL never changes between restarts 🎉"
